spring.application.name=expense-tracker-project-mongodb

server.port=9999

# mongodb configuration
spring.mongodb.uri=mongodb+srv://root:1234@meet.qwmwgtn.mongodb.net/?appName=meet
spring.mongodb.database=moneytrail
spring.data.mongodb.auto-index-creation=true